name: Pantau Replit & Notif Gmail

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Cek Web Asli
        id: cek_web
        run: |
          HASIL=$(curl -sL "https://d652bd72-404d-4613-95d8-2e638af463a9-00-30gd0b03qcoyc.worf.replit.dev")
          
          # Ganti KATA_KUNCI sama teks yang PASTI MUNCUL di web lu pas normal
          if echo "$HASIL" | grep -qi "NOVA"; then
            echo "status=aman" >> $GITHUB_ENV
            echo "Aman, server melek!"
          else
            echo "status=mati" >> $GITHUB_ENV
            echo "Ketutupan ASCII / Mati!"
          fi

      - name: Kirim Email Notifikasi
        if: env.status == 'mati'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🚨 Woy! Server Replit Ketiduran!"
          to: "fadilahalhabsyi78@gmail.com" # GANTI SAMA EMAIL LU
          from: "GitHub Actions Bot"
          body: "Bro, server Replit lu kayaknya lagi pingsan atau ketutupan layar ASCII nih. Buruan bangunin!"
